version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://<Ip-Address>:8000

  # Backend service
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    volumes:
      - ./backend/hf_models:/root/.cache/huggingface/hub
      # - ./backend/ocr_models:/root/.EasyOCR
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Celery worker
  celery:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./backend/hf_models:/root/.cache/huggingface/hub
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

volumes:
  redis_data:
